// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQEo_AhQWMbON1b_zj72yFtplkuj1qrkI',
    appId: '1:792541715569:android:ef3a6bfc74046005924fd0',
    messagingSenderId: '792541715569',
    projectId: 'ecommerce-d5414',
    databaseURL: 'https://ecommerce-d5414-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-d5414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv5smABje29M_S900u8gvOu-qQ-Wb6il8',
    appId: '1:792541715569:ios:aa218f325ba9483b924fd0',
    messagingSenderId: '792541715569',
    projectId: 'ecommerce-d5414',
    databaseURL: 'https://ecommerce-d5414-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-d5414.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
