// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV3yAKxPQjU4mPxvLE8-EcCgsa3QzPFSE',
    appId: '1:633365782640:android:224e27e923be55fb7214b5',
    messagingSenderId: '633365782640',
    projectId: 'firbase-chatapp-93c5b',
    databaseURL: 'https://firbase-chatapp-93c5b-default-rtdb.firebaseio.com',
    storageBucket: 'firbase-chatapp-93c5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL3IS3EN6QKFjnvrx2c1Ktge3EoOMojdY',
    appId: '1:633365782640:ios:a9dd7074f028c3f47214b5',
    messagingSenderId: '633365782640',
    projectId: 'firbase-chatapp-93c5b',
    databaseURL: 'https://firbase-chatapp-93c5b-default-rtdb.firebaseio.com',
    storageBucket: 'firbase-chatapp-93c5b.appspot.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

}